<?xml version="1.0"?>
<package format="2">
  <name>ad1_socket</name>
  <version>0.1.0</version>
  <description>The ad1_socket package</description>
    <maintainer email="swpark@todo.todo">swpark</maintainer>
    <license>Apache 2.0</license>

    <buildtool_depend>catkin</buildtool_depend>

    <build_depend>std_msgs</build_depend>
    <exec_depend>std_msgs</exec_depend>
    <build_depend>roscpp</build_depend>
    <exec_depend>roscpp</exec_depend>
    <build_depend>albabot_msgs</build_depend>
    <exec_depend>albabot_msgs</exec_depend>

    <export>
    </export>

</package>
