// Generated by gencpp from file albabot_msgs/CanMsg.msg
// DO NOT EDIT!


#ifndef ALBABOT_MSGS_MESSAGE_CANMSG_H
#define ALBABOT_MSGS_MESSAGE_CANMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace albabot_msgs
{
template <class ContainerAllocator>
struct CanMsg_
{
  typedef CanMsg_<ContainerAllocator> Type;

  CanMsg_()
    : id(0)
    , dlc(0)
    , data()  {
    }
  CanMsg_(const ContainerAllocator& _alloc)
    : id(0)
    , dlc(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef uint8_t _dlc_type;
  _dlc_type dlc;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::albabot_msgs::CanMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::albabot_msgs::CanMsg_<ContainerAllocator> const> ConstPtr;

}; // struct CanMsg_

typedef ::albabot_msgs::CanMsg_<std::allocator<void> > CanMsg;

typedef boost::shared_ptr< ::albabot_msgs::CanMsg > CanMsgPtr;
typedef boost::shared_ptr< ::albabot_msgs::CanMsg const> CanMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::albabot_msgs::CanMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::albabot_msgs::CanMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace albabot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'albabot_msgs': ['/home/swpark/mywork/albabot_ad4/sw/albabot_ad4_ws/src/albabot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::albabot_msgs::CanMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::albabot_msgs::CanMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::albabot_msgs::CanMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::albabot_msgs::CanMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::albabot_msgs::CanMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::albabot_msgs::CanMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::albabot_msgs::CanMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c370a657704c892b1bc831544aca2637";
  }

  static const char* value(const ::albabot_msgs::CanMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc370a657704c892bULL;
  static const uint64_t static_value2 = 0x1bc831544aca2637ULL;
};

template<class ContainerAllocator>
struct DataType< ::albabot_msgs::CanMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "albabot_msgs/CanMsg";
  }

  static const char* value(const ::albabot_msgs::CanMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::albabot_msgs::CanMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32  id\n\
uint8   dlc\n\
uint8[] data\n\
";
  }

  static const char* value(const ::albabot_msgs::CanMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::albabot_msgs::CanMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.dlc);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CanMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::albabot_msgs::CanMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::albabot_msgs::CanMsg_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "dlc: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dlc);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALBABOT_MSGS_MESSAGE_CANMSG_H
