// Generated by gencpp from file albabot_msgs/RobotInfo.msg
// DO NOT EDIT!


#ifndef ALBABOT_MSGS_MESSAGE_ROBOTINFO_H
#define ALBABOT_MSGS_MESSAGE_ROBOTINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace albabot_msgs
{
template <class ContainerAllocator>
struct RobotInfo_
{
  typedef RobotInfo_<ContainerAllocator> Type;

  RobotInfo_()
    : left_enc(0)
    , right_enc(0)
    , sonic()
    , hall()
    , batVoltage(0)
    , agvMissionCount(0)
    , agvStatus(0)
    , agvDirection(0)
    , agvCurrentMission(0)
    , gio(0)  {
    }
  RobotInfo_(const ContainerAllocator& _alloc)
    : left_enc(0)
    , right_enc(0)
    , sonic(_alloc)
    , hall(_alloc)
    , batVoltage(0)
    , agvMissionCount(0)
    , agvStatus(0)
    , agvDirection(0)
    , agvCurrentMission(0)
    , gio(0)  {
  (void)_alloc;
    }



   typedef int64_t _left_enc_type;
  _left_enc_type left_enc;

   typedef int64_t _right_enc_type;
  _right_enc_type right_enc;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _sonic_type;
  _sonic_type sonic;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _hall_type;
  _hall_type hall;

   typedef uint16_t _batVoltage_type;
  _batVoltage_type batVoltage;

   typedef uint16_t _agvMissionCount_type;
  _agvMissionCount_type agvMissionCount;

   typedef uint8_t _agvStatus_type;
  _agvStatus_type agvStatus;

   typedef uint8_t _agvDirection_type;
  _agvDirection_type agvDirection;

   typedef uint8_t _agvCurrentMission_type;
  _agvCurrentMission_type agvCurrentMission;

   typedef uint16_t _gio_type;
  _gio_type gio;





  typedef boost::shared_ptr< ::albabot_msgs::RobotInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::albabot_msgs::RobotInfo_<ContainerAllocator> const> ConstPtr;

}; // struct RobotInfo_

typedef ::albabot_msgs::RobotInfo_<std::allocator<void> > RobotInfo;

typedef boost::shared_ptr< ::albabot_msgs::RobotInfo > RobotInfoPtr;
typedef boost::shared_ptr< ::albabot_msgs::RobotInfo const> RobotInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::albabot_msgs::RobotInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::albabot_msgs::RobotInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace albabot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'albabot_msgs': ['/home/swpark/mywork/albabot_ad4/sw/albabot_ad4_ws/src/albabot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::albabot_msgs::RobotInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::albabot_msgs::RobotInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::albabot_msgs::RobotInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::albabot_msgs::RobotInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::albabot_msgs::RobotInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::albabot_msgs::RobotInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::albabot_msgs::RobotInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a35fb80dba73d0a155e5bcc00fe71f9";
  }

  static const char* value(const ::albabot_msgs::RobotInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a35fb80dba73d0aULL;
  static const uint64_t static_value2 = 0x155e5bcc00fe71f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::albabot_msgs::RobotInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "albabot_msgs/RobotInfo";
  }

  static const char* value(const ::albabot_msgs::RobotInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::albabot_msgs::RobotInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 left_enc\n\
int64 right_enc\n\
uint16[] sonic\n\
uint16[] hall\n\
uint16 batVoltage\n\
uint16 agvMissionCount\n\
uint8 agvStatus\n\
uint8 agvDirection\n\
uint8 agvCurrentMission\n\
uint16 gio\n\
";
  }

  static const char* value(const ::albabot_msgs::RobotInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::albabot_msgs::RobotInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_enc);
      stream.next(m.right_enc);
      stream.next(m.sonic);
      stream.next(m.hall);
      stream.next(m.batVoltage);
      stream.next(m.agvMissionCount);
      stream.next(m.agvStatus);
      stream.next(m.agvDirection);
      stream.next(m.agvCurrentMission);
      stream.next(m.gio);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::albabot_msgs::RobotInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::albabot_msgs::RobotInfo_<ContainerAllocator>& v)
  {
    s << indent << "left_enc: ";
    Printer<int64_t>::stream(s, indent + "  ", v.left_enc);
    s << indent << "right_enc: ";
    Printer<int64_t>::stream(s, indent + "  ", v.right_enc);
    s << indent << "sonic[]" << std::endl;
    for (size_t i = 0; i < v.sonic.size(); ++i)
    {
      s << indent << "  sonic[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.sonic[i]);
    }
    s << indent << "hall[]" << std::endl;
    for (size_t i = 0; i < v.hall.size(); ++i)
    {
      s << indent << "  hall[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.hall[i]);
    }
    s << indent << "batVoltage: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.batVoltage);
    s << indent << "agvMissionCount: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.agvMissionCount);
    s << indent << "agvStatus: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.agvStatus);
    s << indent << "agvDirection: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.agvDirection);
    s << indent << "agvCurrentMission: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.agvCurrentMission);
    s << indent << "gio: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.gio);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALBABOT_MSGS_MESSAGE_ROBOTINFO_H
