// Generated by gencpp from file albabot_msgs/CommandResponse.msg
// DO NOT EDIT!


#ifndef ALBABOT_MSGS_MESSAGE_COMMANDRESPONSE_H
#define ALBABOT_MSGS_MESSAGE_COMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <albabot_msgs/CanMsg.h>

namespace albabot_msgs
{
template <class ContainerAllocator>
struct CommandResponse_
{
  typedef CommandResponse_<ContainerAllocator> Type;

  CommandResponse_()
    : can_msg()
    , result(0)  {
    }
  CommandResponse_(const ContainerAllocator& _alloc)
    : can_msg(_alloc)
    , result(0)  {
  (void)_alloc;
    }



   typedef  ::albabot_msgs::CanMsg_<ContainerAllocator>  _can_msg_type;
  _can_msg_type can_msg;

   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::albabot_msgs::CommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::albabot_msgs::CommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CommandResponse_

typedef ::albabot_msgs::CommandResponse_<std::allocator<void> > CommandResponse;

typedef boost::shared_ptr< ::albabot_msgs::CommandResponse > CommandResponsePtr;
typedef boost::shared_ptr< ::albabot_msgs::CommandResponse const> CommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::albabot_msgs::CommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::albabot_msgs::CommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace albabot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'albabot_msgs': ['/home/swpark/mywork/albabot_ad4/sw/albabot_ad4_ws/src/albabot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::albabot_msgs::CommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::albabot_msgs::CommandResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::albabot_msgs::CommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::albabot_msgs::CommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::albabot_msgs::CommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::albabot_msgs::CommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::albabot_msgs::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0b8079c27ffa44e0706d5848ee8a425";
  }

  static const char* value(const ::albabot_msgs::CommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0b8079c27ffa44eULL;
  static const uint64_t static_value2 = 0x0706d5848ee8a425ULL;
};

template<class ContainerAllocator>
struct DataType< ::albabot_msgs::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "albabot_msgs/CommandResponse";
  }

  static const char* value(const ::albabot_msgs::CommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::albabot_msgs::CommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "CanMsg  can_msg\n\
uint8   result\n\
\n\
\n\
================================================================================\n\
MSG: albabot_msgs/CanMsg\n\
uint32  id\n\
uint8   dlc\n\
uint8[] data\n\
";
  }

  static const char* value(const ::albabot_msgs::CommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::albabot_msgs::CommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.can_msg);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::albabot_msgs::CommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::albabot_msgs::CommandResponse_<ContainerAllocator>& v)
  {
    s << indent << "can_msg: ";
    s << std::endl;
    Printer< ::albabot_msgs::CanMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.can_msg);
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALBABOT_MSGS_MESSAGE_COMMANDRESPONSE_H
