// Generated by gencpp from file albabot_msgs/Command.msg
// DO NOT EDIT!


#ifndef ALBABOT_MSGS_MESSAGE_COMMAND_H
#define ALBABOT_MSGS_MESSAGE_COMMAND_H

#include <ros/service_traits.h>


#include <albabot_msgs/CommandRequest.h>
#include <albabot_msgs/CommandResponse.h>


namespace albabot_msgs
{

struct Command
{

typedef CommandRequest Request;
typedef CommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Command
} // namespace albabot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::albabot_msgs::Command > {
  static const char* value()
  {
    return "6013552e42710c2dd3ab177183a38018";
  }

  static const char* value(const ::albabot_msgs::Command&) { return value(); }
};

template<>
struct DataType< ::albabot_msgs::Command > {
  static const char* value()
  {
    return "albabot_msgs/Command";
  }

  static const char* value(const ::albabot_msgs::Command&) { return value(); }
};


// service_traits::MD5Sum< ::albabot_msgs::CommandRequest> should match 
// service_traits::MD5Sum< ::albabot_msgs::Command > 
template<>
struct MD5Sum< ::albabot_msgs::CommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::albabot_msgs::Command >::value();
  }
  static const char* value(const ::albabot_msgs::CommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::albabot_msgs::CommandRequest> should match 
// service_traits::DataType< ::albabot_msgs::Command > 
template<>
struct DataType< ::albabot_msgs::CommandRequest>
{
  static const char* value()
  {
    return DataType< ::albabot_msgs::Command >::value();
  }
  static const char* value(const ::albabot_msgs::CommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::albabot_msgs::CommandResponse> should match 
// service_traits::MD5Sum< ::albabot_msgs::Command > 
template<>
struct MD5Sum< ::albabot_msgs::CommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::albabot_msgs::Command >::value();
  }
  static const char* value(const ::albabot_msgs::CommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::albabot_msgs::CommandResponse> should match 
// service_traits::DataType< ::albabot_msgs::Command > 
template<>
struct DataType< ::albabot_msgs::CommandResponse>
{
  static const char* value()
  {
    return DataType< ::albabot_msgs::Command >::value();
  }
  static const char* value(const ::albabot_msgs::CommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALBABOT_MSGS_MESSAGE_COMMAND_H
